# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EPSxfCcvH3w9qFW51kLET5VPiNWmndN7
"""

def gcd(a, b):
    a = abs(a);
    b = abs(b);

    k = 1;
    while (a % 2 == 0 and b % 2 == 0):
        a /= 2
        b /= 2
        k *= 2

    p = 1
    q = 0
    r = 0
    s = 1
    while (a>0 and b>0):
        if (a >= b):
            a -= b
            p -= r
            q -= s;
        else:
            b -= a; r -= p; s -= q;
    return (p, q, k * a) if a!=0 else (r, s, k * b)

def diofant(a,b,c):
    print(f"a = {a}\nb = {b}\nc = {c}")

    ans = gcd(a, b)
    u = ans[0]
    v = ans[1]
    d = ans[2]
    s = 0
    t = 0
    print(f"{u} * {a} + {v} * {b} = {d}")

    if (c % d == 0):
        s = int(u * (c / d))
        t = int(v * (c / d))
        print(f"{s} * {a} + {t} * {b} = {c}")
    else:
        print(f"s * {a} + t * {b} = {c} has no answer in integer numbers")

    print(f"d = {d}");
    print(f"u = {u}");
    print(f"v = {v}");
    print(f"s = {s}");
    print(f"t = {t}");
    print("---------------------------------------");

diofant(66, 15, 21);
diofant(7705636, 7121729, 7519);
diofant(2101106450462279, 628817143587126, 45162);

diofant(585, 174, 15)

